# Use an official Python runtime as a parent image
FROM python:3.10-slim-bullseye

# Set the working directory in the container
WORKDIR /app


# Install Poetry
RUN pip install --no-cache-dir poetry

# Copy Poetry files and install dependencies
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
	&& poetry install --no-interaction --no-ansi --no-root

# Copy the entire application code to the working directory
# This is important as worker needs access to app.celery.tasks, app.core.config etc.
COPY . .

# Make Celery worker entrypoint executable
RUN chmod +x /app/deployment/celery_worker_entrypoint.sh

# Set the entrypoint for the Celery worker
ENTRYPOINT ["/app/deployment/celery_worker_entrypoint.sh"]

# Default command for the worker (can be overridden in docker-compose)
CMD []
